application: quartermaster-bne
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- deferred: on

inbound_services:
- warmup

skip_files:
- ^(.*/)?app\.ya?ml
- ^(.*/)?index\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$

error_handlers:
- error_code: over_quota
  file: error_pages/over_quota.html
- error_code: timeout
  file: error_pages/timeout.html

handlers:
# Static files (stylesheet, etc)
- url: /static
  static_dir: quartermaster/static

# Special static file rule for robots.txt
- url: /robots.txt
  static_files: quartermaster/static/robots.txt
  upload: quartermaster/static/robots.txt  

# Special static file rule for favicon.ico
- url: /favicon.ico
  static_files: quartermaster/static/favicon.ico
  upload: quartermaster/static/favicon.ico

# Handler for high-security content (AJAX endpoints, etc)
- url: /api/.*
  script: djangoappengine.main.main.application
  login: required
  auth_fail_action: unauthorized

# Handler for low-security content (Our app can handle authentication for these pages)
- url: /.*
  script: djangoappengine.main.main.application
  
